/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.BufferedReader;
import java.util.Scanner;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
/**
 *
 * @author Enoc
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Ingre = new javax.swing.JPanel();
        titulo_Personal1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        evento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lugar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        guardar_InfoP = new javax.swing.JButton();
        boton_MenuP_Ingreso = new javax.swing.JButton();
        salir_IngresoP = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        text_Buscador = new javax.swing.JTextField();
        buscar_InfoP = new javax.swing.JButton();
        eliminar_InfoP = new javax.swing.JButton();
        modificar_InfoP = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        receiver = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boton_Enviar = new javax.swing.JButton();
        asunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo_Personal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_Personal1.setText("  INFORMACION DE AGENDA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Evento:");

        evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Lugar:");

        lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hora:");

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });

        guardar_InfoP.setBackground(new java.awt.Color(51, 102, 0));
        guardar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardar_InfoP.setForeground(new java.awt.Color(255, 255, 204));
        guardar_InfoP.setText("GUARDAR NUEVO");
        guardar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_InfoPActionPerformed(evt);
            }
        });

        boton_MenuP_Ingreso.setBackground(new java.awt.Color(51, 102, 0));
        boton_MenuP_Ingreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_MenuP_Ingreso.setForeground(new java.awt.Color(255, 255, 204));
        boton_MenuP_Ingreso.setText("MENU PRINCIPAL");
        boton_MenuP_Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_MenuP_IngresoActionPerformed(evt);
            }
        });

        salir_IngresoP.setBackground(new java.awt.Color(255, 0, 0));
        salir_IngresoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salir_IngresoP.setForeground(new java.awt.Color(255, 255, 204));
        salir_IngresoP.setText("SALIR");
        salir_IngresoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_IngresoPActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Ingrese nombre que desea buscar / modificar");

        buscar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscar_InfoP.setText("BUSCAR");
        buscar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_InfoPActionPerformed(evt);
            }
        });

        eliminar_InfoP.setBackground(new java.awt.Color(255, 51, 51));
        eliminar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar_InfoP.setForeground(new java.awt.Color(255, 255, 204));
        eliminar_InfoP.setText("ELIMINAR EVENTO");
        eliminar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_InfoPActionPerformed(evt);
            }
        });

        modificar_InfoP.setBackground(new java.awt.Color(0, 102, 102));
        modificar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificar_InfoP.setForeground(new java.awt.Color(255, 255, 204));
        modificar_InfoP.setText("MODIFICAR INFORMACION");
        modificar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_InfoPActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("*Este campo no puede ser modificado");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ingrese direccion de correo para notifcar evento");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Asunto:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Mensaje:");

        boton_Enviar.setBackground(new java.awt.Color(51, 153, 0));
        boton_Enviar.setForeground(new java.awt.Color(255, 255, 204));
        boton_Enviar.setText("ENVIAR");
        boton_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EnviarActionPerformed(evt);
            }
        });

        mensaje.setColumns(20);
        mensaje.setRows(5);
        jScrollPane1.setViewportView(mensaje);

        javax.swing.GroupLayout panel_IngreLayout = new javax.swing.GroupLayout(panel_Ingre);
        panel_Ingre.setLayout(panel_IngreLayout);
        panel_IngreLayout.setHorizontalGroup(
            panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addComponent(boton_Enviar)
                        .addGap(18, 18, 18)
                        .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(salir_IngresoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar_InfoP)
                        .addGap(185, 185, 185))
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addComponent(guardar_InfoP)
                        .addGap(31, 31, 31)
                        .addComponent(modificar_InfoP)
                        .addGap(36, 36, 36)
                        .addComponent(eliminar_InfoP)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_IngreLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(49, 49, 49))
                            .addGroup(panel_IngreLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngreLayout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(boton_MenuP_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngreLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo_Personal1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngreLayout.createSequentialGroup()
                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngreLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(9, 9, 9)))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngreLayout.createSequentialGroup()
                        .addComponent(text_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
        );
        panel_IngreLayout.setVerticalGroup(
            panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngreLayout.createSequentialGroup()
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(titulo_Personal1)))
                .addGap(18, 18, 18)
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar_InfoP)
                    .addComponent(boton_MenuP_Ingreso)
                    .addComponent(salir_IngresoP))
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addGap(39, 39, 39)
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton_Enviar))
                    .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardar_InfoP)
                            .addComponent(eliminar_InfoP)
                            .addComponent(modificar_InfoP))
                        .addGap(20, 20, 20))
                    .addGroup(panel_IngreLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_IngreLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel8))
                            .addGroup(panel_IngreLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_IngreLayout.createSequentialGroup()
                                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(38, 38, 38)
                                        .addGroup(panel_IngreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(83, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Ingre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panel_Ingre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_eventoActionPerformed

    private void lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaActionPerformed

    private void guardar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_InfoPActionPerformed
        // TODO add your handling code here:
        informacion_Personal info_P = new informacion_Personal();

        String evento_Ingresado = evento.getText();
        info_P.setEvento(evento_Ingresado);
        //JOptionPane.showMessageDialog(null,"Nombre: " + info_P.getNombre());

        String lugar_Ingresado = lugar.getText();
        info_P.setLugar(lugar_Ingresado);

        String fecha_Ingresado = fecha.getText();
        info_P.setFecha(fecha_Ingresado);

        String hora_Ingresado = hora.getText();
        info_P.setHora(hora_Ingresado);
        
        try{
            FileWriter fichero_Insertar = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt", true);

            fichero_Insertar.write(info_P.getEvento() + "---" + info_P.getLugar() + "---" +
                info_P.getFecha() + "---" + info_P.getHora() + "\r\n");

            fichero_Insertar.close();

            JOptionPane.showMessageDialog(null, "Informacion ingresada con exito.");

        } catch(IOException e) {
            System.out.println("Ocurrio un error al guardar la informacion!");
        }

        JTextField caja;

        for (int i = 0; i < panel_Ingre.getComponentCount(); i++) {
            if(panel_Ingre.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)panel_Ingre.getComponent(i);
                caja.setText("");
            }
        }
        
        asunto.setText("EVENTO: " + evento_Ingresado);
        mensaje.setText("INFORMACION DEL EVENTO:" + "\r\n" + "Lugar: " + lugar_Ingresado + "\r\n" + 
                "Fecha: " + fecha_Ingresado + "\r\n" + "Hora: " 
                + hora_Ingresado);
    }//GEN-LAST:event_guardar_InfoPActionPerformed

    private void boton_MenuP_IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_MenuP_IngresoActionPerformed
        // TODO add your handling code here:
        menu menu_Personal_Ingreso = new menu();
        menu_Personal_Ingreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_MenuP_IngresoActionPerformed

    private void salir_IngresoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_IngresoPActionPerformed
        // TODO add your handling code here:
        login login_Personal = new login();
        login_Personal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salir_IngresoPActionPerformed

    private void buscar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_InfoPActionPerformed
        // TODO add your handling code here
        informacion_Personal info_P = new informacion_Personal();
        //File fichero = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
        FileReader lector_Buscar = null;
        //ArrayList<String> resultado_Consulta = new ArrayList<>();

        JOptionPane.showMessageDialog(null, "IMPORTANTE: Si desea modificar algun valor debe editar el campo y posteriormente utilizar el boton MODIFICAR INFORMACION");

        try{
            File fichero = new File("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
            String linea_Archivo;
            boolean encontrado = false;

            String nombre_Buscar = text_Buscador.getText();

            lector_Buscar = new FileReader(fichero);
            BufferedReader buffer_Lector = new BufferedReader(lector_Buscar);

            while((linea_Archivo=buffer_Lector.readLine()) != null) {
                String[] datos_Busqueda = linea_Archivo.split("---");

                if(datos_Busqueda[0].equals(nombre_Buscar)) {
                    encontrado = true;

                    evento.setText(datos_Busqueda[0]);
                    lugar.setText(datos_Busqueda[1]);
                    fecha.setText(datos_Busqueda[2]);
                    hora.setText(datos_Busqueda[3]);
                }
            }

            if(encontrado == false){
                JOptionPane.showMessageDialog(null, "Informacion no encontrada");
            }

        }catch(IOException e) {
            System.out.println("Ocurrio un error en la busqueda!");
        } finally {

            try{
                if(null == lector_Buscar) {
                    lector_Buscar.close();
                }
            } catch(IOException e2) {
                e2.printStackTrace();
            }
        }
    }//GEN-LAST:event_buscar_InfoPActionPerformed

    private void modificar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_InfoPActionPerformed
        // TODO add your handling code here:
        informacion_Personal modificar_P = new informacion_Personal();
        File fichero_Mod = new File("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
        ArrayList<String> resultado_Consulta = new ArrayList<>();

        if(fichero_Mod.exists()) {

            try{
                String linea_Archivo;

                FileReader lector = new FileReader(fichero_Mod);
                BufferedReader buffer_Lector = new BufferedReader(lector);

                while((linea_Archivo=buffer_Lector.readLine()) != null) {
                    String[] nuevos_Datos = linea_Archivo.split("---");

                    if(!nuevos_Datos[0].equals(text_Buscador.getText())) {
                        resultado_Consulta.add(linea_Archivo);
                    } else{
                        nuevos_Datos[1] = lugar.getText();
                        modificar_P.setLugar(nuevos_Datos[1]);

                        nuevos_Datos[2] = fecha.getText();
                        modificar_P.setFecha(nuevos_Datos[2]);

                        nuevos_Datos[3] = hora.getText();
                        modificar_P.setHora(nuevos_Datos[3]);
                        
                         mensaje.setText("CAMBIO EN LA PROGRAMACION DEL EVENTO" + "\r\n" + "INFORMACION ACTUALIZADA:" + 
                                "\r\n" + "Lugar: " + nuevos_Datos[1] + "\r\n" + "Fecha: " + nuevos_Datos[2] + 
                                "\r\n" + "Hora: " + nuevos_Datos[3]);

                        resultado_Consulta.add(nuevos_Datos[0] + "---" + nuevos_Datos[1] + "---" + nuevos_Datos[2] +
                            "---" + nuevos_Datos[3]);
                    }  
                }
                
                JOptionPane.showMessageDialog(null, "La informacion fue modificada" + "\r\n" + 
                        "Debe enviar un correo con la informacion actualizada ");
                
                lector.close();
                buffer_Lector.close();
                File fichero_Temp = new File("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
                fichero_Temp.delete();
                FileWriter fichero_Nuevo = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
                PrintWriter digitador = new PrintWriter(fichero_Nuevo);

                for (int i = 0; i < resultado_Consulta.size(); i++) {
                    digitador.println(resultado_Consulta.get(i));
                }

                digitador.close();
                fichero_Nuevo.close();

                JTextField caja;
                
                String nombre_Evento = evento.getText();

                for (int i = 0; i < panel_Ingre.getComponentCount(); i++) {
                    if(panel_Ingre.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                        asunto.setText("IMPORTANTE-EVENTO: " + nombre_Evento);
                        caja = (JTextField)panel_Ingre.getComponent(i);
                        caja.setText("");
                    }
                }  
            } catch(IOException e) {
                System.out.println("Ocurrio un error en la busqueda!");
            }
        }
    }//GEN-LAST:event_modificar_InfoPActionPerformed

    private void eliminar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_InfoPActionPerformed
        // TODO add your handling code here:
        informacion_Personal modificar_P = new informacion_Personal();
        File fichero_Mod = new File("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
        ArrayList<String> resultado_Consulta = new ArrayList<>();
        
        JOptionPane.showMessageDialog(null, "La informacion sera eliminada");

        if(fichero_Mod.exists()) {

            try{
                String linea_Archivo;

                FileReader lector = new FileReader(fichero_Mod);
                BufferedReader buffer_Lector = new BufferedReader(lector);

                while((linea_Archivo=buffer_Lector.readLine()) != null) {
                    String[] nuevos_Datos = linea_Archivo.split("---");

                    if(!nuevos_Datos[0].equals(text_Buscador.getText())) {
                        resultado_Consulta.add(linea_Archivo);
                    } else{
                        nuevos_Datos[0] = "";
                        
                        nuevos_Datos[1] = "";
                        modificar_P.setLugar(nuevos_Datos[1]);

                        nuevos_Datos[2] = "";
                        modificar_P.setFecha(nuevos_Datos[2]);

                        nuevos_Datos[3] = "";
                        modificar_P.setHora(nuevos_Datos[3]);

                        resultado_Consulta.add(nuevos_Datos[0] + "" + nuevos_Datos[1] + "" + nuevos_Datos[2] +
                            "" + nuevos_Datos[3]);
                    }
                }
                JOptionPane.showMessageDialog(null, "La informacion fue eliminada");
                
                lector.close();
                buffer_Lector.close();
                File fichero_Temp = new File("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
                fichero_Temp.delete();
                FileWriter fichero_Nuevo = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\agenda.txt");
                PrintWriter digitador = new PrintWriter(fichero_Nuevo);

                for (int i = 0; i < resultado_Consulta.size(); i++) {
                    digitador.println(resultado_Consulta.get(i));
                }

                digitador.close();
                fichero_Nuevo.close();

                JTextField caja;

                for (int i = 0; i < panel_Ingre.getComponentCount(); i++) {
                    if(panel_Ingre.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                        caja = (JTextField)panel_Ingre.getComponent(i);
                        caja.setText("");
                    }
                }
            } catch(IOException e) {
                System.out.println("Ocurrio un error en la busqueda!");
            }
        }
    }//GEN-LAST:event_eliminar_InfoPActionPerformed

    private void boton_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EnviarActionPerformed
        // TODO add your handling code here:
        Properties propiedad = new Properties();
        propiedad.setProperty("mail.smtp.host", "smtp.gmail.com");
        propiedad.setProperty("mail.smtp.starttls.enable", "true");
        propiedad.setProperty("mail.smtp.port", "587");
        propiedad.setProperty("mail.smtp.auth", "true");
        
        Session sesion = Session.getDefaultInstance(propiedad);
        
        String correoEnvia = "prograunouh@gmail.com";
        String contrasena = "PrograUnoUh07";
        String destinatario = receiver.getText();
        String subject = asunto.getText();
        String message = mensaje.getText();
        
        MimeMessage mail = new MimeMessage(sesion);
        
        try {
            mail.setFrom(new InternetAddress(correoEnvia));
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(destinatario));
            mail.setSubject(subject);
            mail.setText(message);
            
            Transport transporte = sesion.getTransport("smtp");
            transporte.connect(correoEnvia,contrasena);
            transporte.sendMessage(mail,mail.getRecipients(Message.RecipientType.TO));
            transporte.close();
            
            JOptionPane.showMessageDialog(null, "Correo enviado");
            
        } catch (AddressException ex) {
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JTextField caja;

        for (int i = 0; i < panel_Ingre.getComponentCount(); i++) {
            if(panel_Ingre.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                mensaje.setText(" ");
                caja = (JTextField)panel_Ingre.getComponent(i);
                caja.setText("");   
            }
        }
    }//GEN-LAST:event_boton_EnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }
    
    public class informacion_Personal {
        
        private String evento;
        private String lugar;
        private String fecha;
        private String hora;
          
        public informacion_Personal() {
            
        }
        
        public informacion_Personal(String evento, String lugar, String fecha, String hora) {
            
            this.evento = evento;
            this.lugar = lugar;
            this.fecha = fecha;
            this.hora = hora;
        }

        public String getEvento() {
            return evento;
        }

        public void setEvento(String evento) {
            this.evento = evento;
        }

        public String getLugar() {
            return lugar;
        }

        public void setLugar(String lugar) {
            this.lugar = lugar;
        }

        public String getFecha() {
            return fecha;
        }

        public void setFecha(String fecha) {
            this.fecha = fecha;
        }

        public String getHora() {
            return hora;
        }

        public void setHora(String hora) {
            this.hora = hora;
        }
        
        public void ingresar_informacion(){
            
        }
        
        private boolean getComponentCount() {
            throw new UnsupportedOperationException("Not supported yet.");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asunto;
    private javax.swing.JButton boton_Enviar;
    private javax.swing.JButton boton_MenuP_Ingreso;
    private javax.swing.JButton buscar_InfoP;
    private javax.swing.JButton eliminar_InfoP;
    private javax.swing.JTextField evento;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton guardar_InfoP;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lugar;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JButton modificar_InfoP;
    private javax.swing.JPanel panel_Ingre;
    private javax.swing.JTextField receiver;
    private javax.swing.JButton salir_IngresoP;
    private javax.swing.JTextField text_Buscador;
    private javax.swing.JLabel titulo_Personal1;
    // End of variables declaration//GEN-END:variables

    }
