/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.BufferedReader;
import java.util.Scanner;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Enoc
 */
public class ingresar_Personal extends javax.swing.JFrame {

    /**
     * Creates new form ingresar_Personal
     */
    public ingresar_Personal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panel_Ingreso = new javax.swing.JPanel();
        titulo_Personal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        organizacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        puesto = new javax.swing.JTextField();
        archivar = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mostrar = new javax.swing.JTextField();
        guardar_InfoP = new javax.swing.JButton();
        boton_MenuP_Ingreso = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pagina_Web = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        direccion_Im = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tel_Trabajo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tel_Personal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        num_Fax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        direccion_Trabajo = new javax.swing.JTextField();
        salir_IngresoP = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        text_Buscador = new javax.swing.JTextField();
        buscar_InfoP = new javax.swing.JButton();
        eliminar_InfoP = new javax.swing.JButton();
        modificar_InfoP = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("panel_PrincipalP");

        titulo_Personal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_Personal.setText("INGRESO DE INFORMACION PERSONAL");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Organizacion:");

        organizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizacionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Puesto:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Archivar como:");

        puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoActionPerformed(evt);
            }
        });

        archivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivarActionPerformed(evt);
            }
        });

        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mostrar como:");

        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        guardar_InfoP.setBackground(new java.awt.Color(51, 102, 0));
        guardar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardar_InfoP.setForeground(new java.awt.Color(255, 255, 204));
        guardar_InfoP.setText("GUARDAR NUEVO");
        guardar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_InfoPActionPerformed(evt);
            }
        });

        boton_MenuP_Ingreso.setBackground(new java.awt.Color(51, 102, 0));
        boton_MenuP_Ingreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_MenuP_Ingreso.setForeground(new java.awt.Color(255, 255, 204));
        boton_MenuP_Ingreso.setText("MENU PRINCIPAL");
        boton_MenuP_Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_MenuP_IngresoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Pagina web:");

        pagina_Web.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina_WebActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Direccion IM:");

        direccion_Im.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_ImActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Tel. Trabajo:");

        tel_Trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_TrabajoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tel. Personal:");

        tel_Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_PersonalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Fax Oficina:");

        num_Fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_FaxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Direccion Trabajo:");

        direccion_Trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_TrabajoActionPerformed(evt);
            }
        });

        salir_IngresoP.setBackground(new java.awt.Color(255, 0, 0));
        salir_IngresoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salir_IngresoP.setForeground(new java.awt.Color(255, 255, 204));
        salir_IngresoP.setText("SALIR");
        salir_IngresoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_IngresoPActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Ingrese nombre que desea buscar / modificar");

        buscar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buscar_InfoP.setText("BUSCAR");
        buscar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_InfoPActionPerformed(evt);
            }
        });

        eliminar_InfoP.setBackground(new java.awt.Color(255, 51, 51));
        eliminar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminar_InfoP.setForeground(new java.awt.Color(255, 255, 204));
        eliminar_InfoP.setText("ELIMINAR REGISTROS");
        eliminar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_InfoPActionPerformed(evt);
            }
        });

        modificar_InfoP.setBackground(new java.awt.Color(0, 102, 102));
        modificar_InfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificar_InfoP.setForeground(new java.awt.Color(255, 255, 204));
        modificar_InfoP.setText("MODIFICAR INFORMACION");
        modificar_InfoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_InfoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_IngresoLayout = new javax.swing.GroupLayout(panel_Ingreso);
        panel_Ingreso.setLayout(panel_IngresoLayout);
        panel_IngresoLayout.setHorizontalGroup(
            panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngresoLayout.createSequentialGroup()
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_IngresoLayout.createSequentialGroup()
                                .addComponent(boton_MenuP_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(salir_IngresoP)
                                .addGap(213, 213, 213)
                                .addComponent(buscar_InfoP))
                            .addGroup(panel_IngresoLayout.createSequentialGroup()
                                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(23, 23, 23)
                                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(archivar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pagina_Web, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7)
                                    .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_IngresoLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(organizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_IngresoLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(58, 58, 58)
                                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(panel_IngresoLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(28, 28, 28)
                                                .addComponent(num_Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel_IngresoLayout.createSequentialGroup()
                                                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel9))
                                                .addGap(18, 18, 18)
                                                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tel_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tel_Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panel_IngresoLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(direccion_Im, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(direccion_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(eliminar_InfoP))))))
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addComponent(titulo_Personal, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_IngresoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addComponent(guardar_InfoP)
                        .addGap(21, 21, 21)
                        .addComponent(modificar_InfoP))
                    .addComponent(text_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        panel_IngresoLayout.setVerticalGroup(
            panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_IngresoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_Personal)
                    .addComponent(jLabel13))
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton_MenuP_Ingreso)
                            .addComponent(salir_IngresoP)))
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(buscar_InfoP)))
                .addGap(30, 30, 30)
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(direccion_Im, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(organizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tel_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(archivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pagina_Web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addGap(25, 126, Short.MAX_VALUE)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tel_Personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(num_Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direccion_Trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificar_InfoP)
                            .addComponent(guardar_InfoP))
                        .addGap(18, 18, 18)
                        .addComponent(eliminar_InfoP)
                        .addGap(22, 22, 22))
                    .addGroup(panel_IngresoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_MenuP_IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_MenuP_IngresoActionPerformed
        // TODO add your handling code here:
        menu menu_Personal_Ingreso = new menu();
        menu_Personal_Ingreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_MenuP_IngresoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_nombreActionPerformed

    private void guardar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_InfoPActionPerformed
        // TODO add your handling code here:
        informacion_Personal info_P = new informacion_Personal();
        String nombre_Ingresado = nombre.getText();
        info_P.setNombre(nombre_Ingresado);
        //JOptionPane.showMessageDialog(null,"Nombre: " + info_P.getNombre());
        
        String organizacion_Ingresado = organizacion.getText();
        info_P.setOrganizacion(organizacion_Ingresado);
        
        String puesto_Ingresado = puesto.getText();
        info_P.setPuesto(puesto_Ingresado);
        
        String archivar_Ingresado = archivar.getText();
        info_P.setArchivar(archivar_Ingresado);
        
        String correo_Ingresado = correo.getText();
        info_P.setCorreo(correo_Ingresado);
        
        String mostrar_Ingresado = mostrar.getText();
        info_P.setMostrar_Como(mostrar_Ingresado);
        
        String web_Ingresada = pagina_Web.getText();
        info_P.setPagina_Web(web_Ingresada);
        
        String im_Ingresado = direccion_Im.getText();
        info_P.setDireccion_Im(im_Ingresado);
        
        String telefono_Trab = tel_Trabajo.getText();
        info_P.setTelefono_Trabajo(telefono_Trab);
        
        String telefono_Pers = tel_Personal.getText();
        info_P.setTelefono_Movil(telefono_Pers);
        
        String numero_Fax = num_Fax.getText();
        info_P.setTelefono_Fax(numero_Fax);
        
        String dir_Trabajo = direccion_Trabajo.getText();
        info_P.setDireccion_Trabajo(dir_Trabajo);
        
       
        try{
            FileWriter fichero_Insertar = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt", true);
           
            fichero_Insertar.write(info_P.getNombre() + "---" + info_P.getOrganizacion() + "---" + 
                    info_P.getPuesto() + "---" + info_P.getArchivar() + "---" + info_P.getCorreo() +
                    "---" + info_P.getMostrar_Como() + "---" + info_P.getPagina_Web() + "---" + 
                    info_P.getDireccion_Im() + "---" + info_P.getTelefono_Trabajo() + "---" + 
                    info_P.getTelefono_Movil() + "---" + info_P.getTelefono_Fax() + "---" + 
                    info_P.getDireccion_Trabajo() + "\r\n");
           
            fichero_Insertar.close();
           
        } catch(IOException e) {
            System.out.println("Ocurrio un error al guardar la informacion!");
        }
        
        JTextField caja;
        
        for (int i = 0; i < panel_Ingreso.getComponentCount(); i++) {
            if(panel_Ingreso.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                caja = (JTextField)panel_Ingreso.getComponent(i);
                caja.setText("");
            }
        }
        
        JOptionPane.showMessageDialog(null, "Informacion ingresada con exito.");
    }//GEN-LAST:event_guardar_InfoPActionPerformed

    private void organizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizacionActionPerformed

    private void puestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoActionPerformed

    private void archivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivarActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarActionPerformed

    private void pagina_WebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina_WebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina_WebActionPerformed

    private void direccion_ImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_ImActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_ImActionPerformed

    private void tel_TrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_TrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_TrabajoActionPerformed

    private void tel_PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_PersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_PersonalActionPerformed

    private void num_FaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_FaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_FaxActionPerformed

    private void direccion_TrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_TrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_TrabajoActionPerformed

    private void salir_IngresoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_IngresoPActionPerformed
        // TODO add your handling code here:
        login login_Personal = new login();
        login_Personal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salir_IngresoPActionPerformed

    private void buscar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_InfoPActionPerformed
        // TODO add your handling code here
        informacion_Personal info_P = new informacion_Personal();
        //File fichero = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
        FileReader lector_Buscar = null;
        //ArrayList<String> resultado_Consulta = new ArrayList<>();
        
        JOptionPane.showMessageDialog(null, "Si desea modificar debe editar el campo y posteriormente utilizar el boton MODIFICAR INFORMACION");
        
            try{
                File fichero = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
                String linea_Archivo;
                boolean encontrado = false;
                
                String nombre_Buscar = text_Buscador.getText();
                
                lector_Buscar = new FileReader(fichero);
                BufferedReader buffer_Lector = new BufferedReader(lector_Buscar);
                
                while((linea_Archivo=buffer_Lector.readLine()) != null) {
                    String[] datos_Busqueda = linea_Archivo.split("---");
                    
                    if(datos_Busqueda[0].equals(nombre_Buscar)) {
                        encontrado = true;
                        
                        nombre.setText(datos_Busqueda[0]);
                        organizacion.setText(datos_Busqueda[1]);
                        puesto.setText(datos_Busqueda[2]);
                        archivar.setText(datos_Busqueda[3]);
                        correo.setText(datos_Busqueda[4]);
                        mostrar.setText(datos_Busqueda[5]);
                        pagina_Web.setText(datos_Busqueda[6]);
                        direccion_Im.setText(datos_Busqueda[7]);
                        tel_Trabajo.setText(datos_Busqueda[8]);
                        tel_Personal.setText(datos_Busqueda[9]);
                        num_Fax.setText(datos_Busqueda[10]);
                        direccion_Trabajo.setText(datos_Busqueda[11]);
                    }
                }
                
                if(encontrado == false){
                        JOptionPane.showMessageDialog(null, "Informacion no encontrada");
                }
                
            }catch(IOException e) {
                System.out.println("Ocurrio un error en la busqueda!");
            } finally {
            
                try{                
                    if(null == lector_Buscar) {
                        lector_Buscar.close();
                    }
            } catch(IOException e2) {
                e2.printStackTrace();
            }
        }
    }//GEN-LAST:event_buscar_InfoPActionPerformed

    private void modificar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_InfoPActionPerformed
        // TODO add your handling code here:
        informacion_Personal modificar_P = new informacion_Personal();
        File fichero_Mod = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
        ArrayList<String> resultado_Consulta = new ArrayList<>();
        
        if(fichero_Mod.exists()) {
            
            try{
                String linea_Archivo;
                
                FileReader lector = new FileReader(fichero_Mod);
                BufferedReader buffer_Lector = new BufferedReader(lector);
                
                while((linea_Archivo=buffer_Lector.readLine()) != null) {
                    String[] nuevos_Datos = linea_Archivo.split("---");
                    
                    if(!nuevos_Datos[0].equals(text_Buscador.getText())) {
                        resultado_Consulta.add(linea_Archivo);
                    } else{
                        nuevos_Datos[1] = organizacion.getText();
                        modificar_P.setOrganizacion(nuevos_Datos[1]);
                        
                        nuevos_Datos[2] = puesto.getText();
                        modificar_P.setPuesto(nuevos_Datos[2]);
                        
                        nuevos_Datos[3] = archivar.getText();
                        modificar_P.setArchivar(nuevos_Datos[3]);
                        
                        nuevos_Datos[4] = correo.getText();
                        modificar_P.setCorreo(nuevos_Datos[4]);
                        
                        nuevos_Datos[5] = mostrar.getText();
                        modificar_P.setMostrar_Como(nuevos_Datos[5]);

                        nuevos_Datos[6] = pagina_Web.getText();
                        modificar_P.setPagina_Web(nuevos_Datos[6]);
                        
                        nuevos_Datos[7] = direccion_Im.getText();
                        modificar_P.setDireccion_Im(nuevos_Datos[7]);
                        
                        nuevos_Datos[8] = tel_Trabajo.getText();
                        modificar_P.setTelefono_Trabajo(nuevos_Datos[8]);
                        
                        nuevos_Datos[9] = tel_Personal.getText();
                        modificar_P.setTelefono_Movil(nuevos_Datos[9]);
 
                        nuevos_Datos[10] = num_Fax.getText();
                        modificar_P.setTelefono_Fax(nuevos_Datos[10]);
                        
                        nuevos_Datos[11] = direccion_Trabajo.getText();
                        modificar_P.setDireccion_Trabajo(nuevos_Datos[11]);
                            
                        resultado_Consulta.add(nuevos_Datos[0] + "---" + nuevos_Datos[1] + "---" + nuevos_Datos[2] + 
                            "---" + nuevos_Datos[3] + "---" + nuevos_Datos[4] + "---" + nuevos_Datos[5] + "---" + 
                                nuevos_Datos[6] + "---" + nuevos_Datos[7] + "---" + nuevos_Datos[8] + "---" + 
                                nuevos_Datos[9] + "---" + nuevos_Datos[10] + "---" + nuevos_Datos[11]);
                        }
                    }
                lector.close();
                buffer_Lector.close();
                File fichero_Temp = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
                fichero_Temp.delete();
                FileWriter fichero_Nuevo = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
                PrintWriter digitador = new PrintWriter(fichero_Nuevo);
                
                for (int i = 0; i < resultado_Consulta.size(); i++) {
                    digitador.println(resultado_Consulta.get(i));
                }
                
                digitador.close();
                fichero_Nuevo.close();
                
                JTextField caja;
        
                for (int i = 0; i < panel_Ingreso.getComponentCount(); i++) {
                    if(panel_Ingreso.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                        caja = (JTextField)panel_Ingreso.getComponent(i);
                        caja.setText("");
                    }
                }
            } catch(IOException e) {
                System.out.println("Ocurrio un error en la busqueda!");
            }
        }
    }//GEN-LAST:event_modificar_InfoPActionPerformed

    private void eliminar_InfoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_InfoPActionPerformed
        // TODO add your handling code here:
        informacion_Personal modificar_P = new informacion_Personal();
        File fichero_Mod = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
        ArrayList<String> resultado_Consulta = new ArrayList<>();
        
        JOptionPane.showMessageDialog(null, "La informacion de este registro sera eliminada.");
        
        if(fichero_Mod.exists()) {
            
            try{
                String linea_Archivo;
                
                FileReader lector = new FileReader(fichero_Mod);
                BufferedReader buffer_Lector = new BufferedReader(lector);
                
                while((linea_Archivo=buffer_Lector.readLine()) != null) {
                    String[] nuevos_Datos = linea_Archivo.split("---");
                    
                    if(!nuevos_Datos[0].equals(text_Buscador.getText())) {
                        resultado_Consulta.add(linea_Archivo);
                    } else{
                        nuevos_Datos[0] = "";
                        modificar_P.setNombre(nuevos_Datos[0]);
                        
                        nuevos_Datos[1] = "";
                        modificar_P.setOrganizacion(nuevos_Datos[1]);
                        
                        nuevos_Datos[2] = "";
                        modificar_P.setPuesto(nuevos_Datos[2]);
                        
                        nuevos_Datos[3] = "";
                        modificar_P.setArchivar(nuevos_Datos[3]);
                        
                        nuevos_Datos[4] = "";
                        modificar_P.setCorreo(nuevos_Datos[4]);
                        
                        nuevos_Datos[5] = "";
                        modificar_P.setMostrar_Como(nuevos_Datos[5]);

                        nuevos_Datos[6] = "";
                        modificar_P.setPagina_Web(nuevos_Datos[6]);
                        
                        nuevos_Datos[7] = "";
                        modificar_P.setDireccion_Im(nuevos_Datos[7]);
                        
                        nuevos_Datos[8] = "";
                        modificar_P.setTelefono_Trabajo(nuevos_Datos[8]);
                        
                        nuevos_Datos[9] = "";
                        modificar_P.setTelefono_Movil(nuevos_Datos[9]);
 
                        nuevos_Datos[10] = "";
                        modificar_P.setTelefono_Fax(nuevos_Datos[10]);
                        
                        nuevos_Datos[11] = "";
                        modificar_P.setDireccion_Trabajo(nuevos_Datos[11]);
                            
                        resultado_Consulta.add(nuevos_Datos[0] + "" + nuevos_Datos[1] 
                                + "---" + nuevos_Datos[2] + "" + nuevos_Datos[3] + "" + nuevos_Datos[4] + "" + 
                                nuevos_Datos[5] + "" + nuevos_Datos[6] + "" + nuevos_Datos[7] + "" + 
                                nuevos_Datos[8] + "" + nuevos_Datos[9] + "" + nuevos_Datos[10] + "" + 
                                nuevos_Datos[11]);
                        }
                    }
                JOptionPane.showMessageDialog(null, "Informacion eliminada con exito.");
                
                lector.close();
                buffer_Lector.close();
                File fichero_Temp = new File("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
                fichero_Temp.delete();
                FileWriter fichero_Nuevo = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt");
                PrintWriter digitador = new PrintWriter(fichero_Nuevo);
                
                for (int i = 0; i < resultado_Consulta.size(); i++) {
                    digitador.println(resultado_Consulta.get(i));
                }
                
                digitador.close();
                fichero_Nuevo.close();
                
                JTextField caja;
        
                for (int i = 0; i < panel_Ingreso.getComponentCount(); i++) {
                    if(panel_Ingreso.getComponent(i).getClass().getName().equals("javax.swing.JTextField")){
                        caja = (JTextField)panel_Ingreso.getComponent(i);
                        caja.setText("");
                    }
                }
            } catch(IOException e) {
                System.out.println("Ocurrio un error en la busqueda!");
            }
        }
    }//GEN-LAST:event_eliminar_InfoPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresar_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresar_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresar_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresar_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresar_Personal().setVisible(true);
            }
        });
    }
    
    public class informacion_Personal {
        
        private String nombre;
        private String organizacion;
        private String archivar;
        private String puesto;
        private String correo;
        private String mostrar_Como;
        private String pagina_Web;
        private String direccion_Im;
        private String telefono_Trabajo;
        private String telefono_Fax;
        private String telefono_Movil;
        private String direccion_Trabajo;
          
        public informacion_Personal() {
            
        }
        
        public informacion_Personal(String nombre, String organizacion, String archivar, String puesto, String correo,
                String mostrar_Como, String pagina_Web, String direccion_Im, String telefono_trabajo, 
                String telefono_Fax, String telefono_Movil, String direccion_Trabajo) {
            
            this.nombre = nombre;
            this.organizacion = organizacion;
            this.puesto = puesto;
            this.archivar = archivar;
            this.correo = correo;
            this.mostrar_Como = mostrar_Como;
            this.pagina_Web = pagina_Web;
            this.direccion_Im = direccion_Im;
            this.telefono_Trabajo = telefono_trabajo;
            this.telefono_Fax = telefono_Fax;
            this.telefono_Movil = telefono_Movil;
            this.direccion_Trabajo = direccion_Trabajo;
        }

        public String getNombre() {
            return nombre;
        }

        public void setNombre(String nombre) {
            this.nombre = nombre;
        }

        public String getOrganizacion() {
            return organizacion;
        }

        public void setOrganizacion(String organizacion) {
            this.organizacion = organizacion;
        }

        public String getArchivar() {
            return archivar;
        }

        public void setArchivar(String archivar) {
            this.archivar = archivar;
        }

        public String getPuesto() {
            return puesto;
        }

        public void setPuesto(String puesto) {
            this.puesto = puesto;
        }

        public String getCorreo() {
            return correo;
        }

        public void setCorreo(String correo) {
            this.correo = correo;
        }

        public String getMostrar_Como() {
            return mostrar_Como;
        }

        public void setMostrar_Como(String mostrar_Como) {
            this.mostrar_Como = mostrar_Como;
        }

        public String getPagina_Web() {
            return pagina_Web;
        }

        public void setPagina_Web(String pagina_Web) {
            this.pagina_Web = pagina_Web;
        }

        public String getDireccion_Im() {
            return direccion_Im;
        }

        public void setDireccion_Im(String direccion_Im) {
            this.direccion_Im = direccion_Im;
        }

        public String getTelefono_Trabajo() {
            return telefono_Trabajo;
        }

        public void setTelefono_Trabajo(String telefono_Trabajo) {
            this.telefono_Trabajo = telefono_Trabajo;
        }

        public String getTelefono_Fax() {
            return telefono_Fax;
        }

        public void setTelefono_Fax(String telefono_Fax) {
            this.telefono_Fax = telefono_Fax;
        }

        public String getTelefono_Movil() {
            return telefono_Movil;
        }

        public void setTelefono_Movil(String telefono_Movil) {
            this.telefono_Movil = telefono_Movil;
        }

        public String getDireccion_Trabajo() {
            return direccion_Trabajo;
        }

        public void setDireccion_Trabajo(String direccion_Trabajo) {
            this.direccion_Trabajo = direccion_Trabajo;
        }
        
        public void ingresar_informacion(){
            
        }

        private boolean getComponentCount() {
            throw new UnsupportedOperationException("Not supported yet.");
        }
        
    }
    
    /*public void insertar(){
       informacion_Personal personal_Info = new informacion_Personal();
       
       try{
           FileWriter fichero_Insertar = new FileWriter("C:\\proyecto_Final_Enoc_Sibaja\\informacion_Personal.txt", 
                   true);
           
           fichero_Insertar.write(personal_Info.getNombre() + "---" + personal_Info.getOrganizacion() + "---" + 
                   personal_Info.getPuesto() + "---" + personal_Info.getArchivar() + "---" + personal_Info.getCorreo() +
                   "---" + personal_Info.getMostrar_Como() + "---" + personal_Info.getPagina_Web() + "---" + 
                   personal_Info.getDireccion_Im() + "---" + personal_Info.getTelefono_Trabajo() + "---" + 
                   personal_Info.getTelefono_Movil() + "---" + personal_Info.getTelefono_Fax() + "---" + 
                   personal_Info.getDireccion_Trabajo() + "\r\n");
           
           fichero_Insertar.close();
           
       } catch(IOException e) {
           System.out.println("Ocurrio un error al guardar la informacion!");
       }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField archivar;
    private javax.swing.JButton boton_MenuP_Ingreso;
    private javax.swing.JButton buscar_InfoP;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion_Im;
    private javax.swing.JTextField direccion_Trabajo;
    private javax.swing.JButton eliminar_InfoP;
    private javax.swing.JButton guardar_InfoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificar_InfoP;
    private javax.swing.JTextField mostrar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField num_Fax;
    private javax.swing.JTextField organizacion;
    private javax.swing.JTextField pagina_Web;
    private javax.swing.JPanel panel_Ingreso;
    private javax.swing.JTextField puesto;
    private javax.swing.JButton salir_IngresoP;
    private javax.swing.JTextField tel_Personal;
    private javax.swing.JTextField tel_Trabajo;
    private javax.swing.JTextField text_Buscador;
    private javax.swing.JLabel titulo_Personal;
    // End of variables declaration//GEN-END:variables
}
