/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enoc
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_Contact = new javax.swing.JButton();
        boton_IP = new javax.swing.JButton();
        boton_agenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir_Principal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton_Contact.setBackground(new java.awt.Color(0, 51, 51));
        boton_Contact.setForeground(new java.awt.Color(255, 255, 204));
        boton_Contact.setText("CONTACTOS");
        boton_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ContactActionPerformed(evt);
            }
        });

        boton_IP.setBackground(new java.awt.Color(0, 51, 51));
        boton_IP.setForeground(new java.awt.Color(255, 255, 204));
        boton_IP.setText("INFORMACION PERSONAL");
        boton_IP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_IPActionPerformed(evt);
            }
        });

        boton_agenda.setBackground(new java.awt.Color(0, 51, 51));
        boton_agenda.setForeground(new java.awt.Color(255, 255, 204));
        boton_agenda.setText("AGENDA");
        boton_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        salir_Principal.setBackground(new java.awt.Color(255, 0, 0));
        salir_Principal.setForeground(new java.awt.Color(255, 255, 204));
        salir_Principal.setText("SALIR");
        salir_Principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_PrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_IP)
                            .addComponent(boton_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(salir_Principal)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(boton_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(boton_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(boton_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(salir_Principal)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ContactActionPerformed
        // TODO add your handling code here:
        ingresar_Contacto contact =  new ingresar_Contacto();
        contact.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_ContactActionPerformed

    private void boton_IPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_IPActionPerformed
        ingresar_Personal info_P = new ingresar_Personal();
        info_P.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_IPActionPerformed

    private void boton_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agendaActionPerformed
        // TODO add your handling code here:
        Agenda calendar = new Agenda();
        calendar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_agendaActionPerformed

    private void salir_PrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_PrincipalActionPerformed
        // TODO add your handling code here:
        login login_Menu = new login();
        login_Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salir_PrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Contact;
    private javax.swing.JButton boton_IP;
    private javax.swing.JButton boton_agenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir_Principal;
    // End of variables declaration//GEN-END:variables
}
